apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ${namespace}
  name: ${namespace}-control-plane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
%{ for key,value in annotations ~}
          ${key}: ${value}
%{ endfor ~}
%{ if lb_ip != "" }
        service:
          type: LoadBalancer
          loadBalancerIP: ${lb_ip}
          externalTrafficPolicy: Local
          ports:
          - name: status-port
            port: 15020
          - name: http2
            port: 80
          - name: https
            port: 443
          - name: tls
            port: 15443
%{ endif ~}