apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: api-service
  namespace: ${namespace}
spec:
  addOwnerRef: true
  componentKinds:
    - group: core
      kind: ConfigMap
    - group: apps
      kind: Deployment
  descriptor:
    description: ""
    keywords:
      - api-service
      - kubeflow
    links:
      - description: About
        url: ""
    maintainers: []
    owners: []
    type: api-service
    version: v1beta1
  selector:
    matchLabels:
%{ for key,value in labels ~}
      ${key}: ${value}
%{ endfor ~}