apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: kubeflow
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: app.k8s.io
    kind: Application
  descriptor:
    description: application that aggregates all kubeflow applications
    keywords:
    - kubeflow
    links:
    - description: About
      url: https://kubeflow.org
    maintainers:
    - email: jlewi@google.com
      name: Jeremy Lewi
    - email: kam.d.kasravi@intel.com
      name: Kam Kasravi
    owners:
    - email: jlewi@google.com
      name: Jeremy Lewi
    type: kubeflow
    version: v1beta1
  selector:
    matchLabels:
%{ for key,value in labels ~}
      ${key}: ${value}
%{ endfor ~}