apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: workflows.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
      - wf
    singular: workflow
  scope: Namespaced
  version: v1alpha1
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: argo
  namespace: ${namespace}
spec:
  addOwnerRef: true
  componentKinds:
    - group: core
      kind: ConfigMap
    - group: apps
      kind: Deployment
    - group: core
      kind: ServiceAccount
    - group: core
      kind: Service
    - group: networking.istio.io
      kind: VirtualService
  descriptor:
    description:
      Argo Workflows is an open source container-native workflow engine
      for orchestrating parallel jobs on Kubernetes
    keywords:
      - argo
      - kubeflow
    links:
      - description: About
        url: https://github.com/argoproj/argo
    maintainers: []
    owners: []
    type: argo
    version: v1beta1
  selector:
    matchLabels:
%{ for key,value in labels ~}
      ${key}: ${value}
%{ endfor ~}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: argo-ui
  namespace: ${namespace}
spec:
  gateways:
    - kubeflow-gateway
  hosts:
  - kubeflow.${domain_name}
  http:
    - match:
        - uri:
            prefix: /argo/
      rewrite:
        uri: /
      route:
        - destination:
            host: argo-ui.${namespace}.svc.cluster.local
            port:
              number: 80