apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ml-pipeline-viewer-crd
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: viewers.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: Viewer
    listKind: ViewerList
    plural: viewers
    shortNames:
    - vi
    singular: viewer
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipeline-viewers-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
    app: ml-pipeline-viewer-crd
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: ml-pipeline-viewer-kubeflow-pipeline-viewers-admin
rules: []
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
%{ for key,value in labels ~}
    ${key}: ${value}
%{ endfor ~}
  name: pipelines-viewer
  namespace: ${namespace}
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ""
    keywords:
    - pipelines-viewer
    - kubeflow
    links:
    - description: About
      url: ""
    maintainers: []
    owners: []
    type: pipelines-viewer
    version: v1beta1
  selector:
    matchLabels:
%{ for key,value in labels ~}
      ${key}: ${value}
%{ endfor ~}