name: "tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  tests_timeout: "2h"
  golangci_lint_version: "v1.26"
jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0

      - name: Terraform Init
        run: TF_LOG=DEBUG terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tflint
        run: docker run --rm -v $(pwd):/data -t wata727/tflint
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0

      - name: "go vet"
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout=3m0s
          version: ${{ env.golangci_lint_version }}

      - name: "go test"
        env:
          K3S_KUBECONFIG_MODE: 644
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          curl -sfL https://get.k3s.io | sh -s - --disable traefik --disable servicelb
          kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
          go test -v -timeout ${{ env.tests_timeout }} ./...