name: "tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  tests_timeout: "2h"
  golangci_lint_version: "v1.26"
jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Download terraform k8s provider"
        run: |
          wget https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.7.7/terraform-provider-k8s_0.7.7_linux_amd64.tar.gz
          tar xvzf terraform-provider-k8s_0.7.7_linux_amd64.tar.gz && chmod +x terraform-provider-k8s
          mkdir -p ~/.terraform.d/plugins
          mv terraform-provider-k8s ~/.terraform.d/plugins

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tflint
        run: docker run --rm -v $(pwd):/data -t wata727/tflint
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
 #       with:
 #         version: '290.0.1'
 #         project_id: ${{ secrets.GCP_PROJECT_ID }}
 #         service_account_key: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}
 #         export_default_credentials: true

 #     - run: gcloud container clusters get-credentials validation-cluster --region europe-west1 --project ${{ secrets.GCP_PROJECT_ID }}
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "go vet"
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout=3m0s
          version: ${{ env.golangci_lint_version }}

      - name: "go test"
        env:
          K3S_KUBECONFIG_MODE: 644
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          curl -sfL https://get.k3s.io | sh -s -
          go test -timeout ${{ env.tests_timeout }} ./...